/**
 * Events' window onto Inventory's `events_inventory` row.
 *
 * Inventory owns that table: it holds capacity, the reserved/sold counters, the generated
 * `remaining`, and the database constraints that keep them honest. Events reads it to build the
 * projection and writes it exactly once, when an event is published — the schema requires the row
 * to exist from the start, and Inventory exposes no method to call.
 *
 * Both halves are behind interfaces so the read model stays testable without Postgres, and so the
 * write can be handed to Inventory later without touching the publish path.
 */
export interface IEventInventorySnapshot {
  eventId: string;
  capacity: number;
  reserved: number;
  sold: number;
  /** Generated by Postgres as capacity - reserved - sold. */
  remaining: number;
}

export interface IEventInventoryReader {
  findByEventId(eventId: string): Promise<IEventInventorySnapshot | null>;
  /** Batched so a list projection costs one inventory read rather than one per event. */
  findByEventIds(eventIds: string[]): Promise<Map<string, IEventInventorySnapshot>>;
}
