import { EventInventory } from "./event-inventory.model";
import { IConsoleEventRow, IPublishedEventDescriptor, IPublishedEventProjection } from "./event.interface";
import { Event } from "./event.model";

/**
 * Projects a stored row onto the event-owned fields this slice publishes. Selecting explicitly
 * rather than spreading the row keeps internals — slug and createdBy — out of the contract, so a
 * column added later is opt-in instead of leaked by default.
 */
export const toDescriptor = (event: Event): IPublishedEventDescriptor => ({
  id: event.id,
  name: event.name,
  description: event.description,
  venue: event.venue,
  address: event.address,
  coverImage: event.coverImage,
  startsAt: event.starts_at,
  ticketPrice: event.ticketPrice,
  currency: event.currency,
});

/** Absent inventory is reported as null, never as 0 — 0 would read as sold out. */
export const toProjection = (
  descriptor: IPublishedEventDescriptor,
  inventory: EventInventory | null,
): IPublishedEventProjection => ({
  ...descriptor,
  capacity: inventory ? inventory.capacity : null,
  reserved: inventory ? inventory.reserved : null,
  sold: inventory ? inventory.sold : null,
  // `remaining` is generated by Postgres; the inferred type still admits null, so the same
  // arithmetic is the fallback rather than dropping the figure altogether.
  remaining: inventory ? inventory.remaining ?? inventory.capacity - inventory.reserved - inventory.sold : null,
});

export const toConsoleRow = (event: Event, inventory: EventInventory | null): IConsoleEventRow => ({
  ...toProjection(toDescriptor(event), inventory),
  status: event.status,
});
